server:
  port: 9999
spring:
  ai:
    model:
      chat: anthropic
    anthropic:
      api-key: ###
      chat:
        options:
          model: claude-3-7-sonnet-20250219
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8080  #????