server:
  port: 9999
spring:
  ai:
    mcp:
      client:
        toolcallback:
          enabled : true
        sse:
          connections:
            my-weather-server:
              url: http://localhost:8080
    ollama:
      chat:
        options:
          model: llama3.2